apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
  labels:
    apps: db
spec:
  serviceName: "db"
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: gotodo
            - name: POSTGRES_PASSWORD
              value: password
