apiVersion: v1
kind: Pod
metadata:
  name: go-todo
spec:
  containers:
    - name: server
      image: go-todo
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8080
      env:
        - name: DB_USER
          value: gotodo
        - name: DB_PASSWORD
          value: password
    - name: db
      image: postgres:16-alpine
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_USER
          value: gotodo
        - name: POSTGRES_PASSWORD
          value: password
