apiVersion: v1
kind: Service
metadata:
  name: go-todo
spec:
  selector:
    app: go-todo
  ports:
    - name: http
      port: 80
      targetPort: 8080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: go-todo
  labels:
    name: go-todo
spec:
  ingressClassName: "nginx"
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: go-todo
                port:
                  number: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-todo
  labels:
    app: go-todo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-todo
  template:
    metadata:
      labels:
        app: go-todo
    spec:
      containers:
        - name: server
          image: go-todo
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: DB_USER
              value: gotodo
            - name: DB_PASSWORD
              value: password
